# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool:
  vmImage: ubuntu-latest  # Change if needed

steps:
  - script: |
      sudo apt update
      sudo apt install -y wget unzip
      wget -O terraform.zip https://releases.hashicorp.com/terraform/1.6.0/terraform_1.11.2_linux_amd64.zip
      sudo unzip terraform.zip -d /usr/local/bin/
      terraform --version
    displayName: 'Install Terraform'

  - script: terraform init
    displayName: 'Terraform Init'

  - script: terraform plan
